// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace salary.DataLayer.Models;

public partial class Employee
{
    public Guid EmpNo { get; set; }

    public int EmpID { get; set; }

    public string Name { get; set; }

    public decimal Gross { get; set; }

    public decimal Tax { get; set; }

    public decimal Pension { get; set; }

    public decimal Salary { get; set; }
}