// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace salary.DataLayer.Models;

public partial class Tax
{
    public int TaxId { get; set; }

    public decimal FromSalary { get; set; }

    public decimal ToSalary { get; set; }

    public decimal Rate { get; set; }
}